Table movies {
  movieId integer [pk]
  title varchar
  year integer
}

Table genres {
  genreId integer [pk]
  name varchar
}

Table movie_genres {
  movieId integer [ref: > movies.movieId]
  genreId integer [ref: > genres.genreId]
}

Table ratings {
  userId integer
  movieId integer [ref: > movies.movieId]
  rating real
  timestamp varchar
}

Table tags {
  userId integer
  movieId integer [ref: > movies.movieId]
  tag varchar
  timestamp varchar
}

Table links {
  movieId integer [ref: > movies.movieId]
  imdbId integer
  tmdbId integer
}
